### ISSUE TITLE
App does not start with Android 6.0 (SDK 23)

### ISSUE THREAD

**Issue by facco88** [appcelerator-archive/ti.redlaser#6]
Hi, I've built my app with the Ti SDK 5.1.2 and setting the Android targetVersion to 23. The apk is normally compiled but when I open the app on a device with Android 6, it does not start and if I look at the Android Monitor the error is:

`02-22 18:28:32.867: W/V8Object(6234): (KrollRuntimeThread) [263,1183] Runtime disposed, cannot set property 'userAgent'
02-22 18:28:32.953: E/linker(6234): /data/app/com.number18.imperial-2/lib/arm/libti.redlaser.so: has text relocations
02-22 18:28:32.967: E/TiApplication(6234): (KrollRuntimeThread) [86,1269] Sending event: exception on thread: KrollRuntimeThread msg:java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.number18.imperial-2/lib/arm/libti.redlaser.so: has text relocations; Titanium 5.1.2,2015/12/16 19:00,ca822b2
02-22 18:28:32.967: E/TiApplication(6234): java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.number18.imperial-2/lib/arm/libti.redlaser.so: has text relocations
02-22 18:28:32.967: E/TiApplication(6234):  at java.lang.Runtime.loadLibrary(Runtime.java:372)
02-22 18:28:32.967: E/TiApplication(6234):  at java.lang.System.loadLibrary(System.java:1076)
02-22 18:28:32.967: E/TiApplication(6234):  at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:132)
02-22 18:28:32.967: E/TiApplication(6234):  at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:99)
02-22 18:28:32.967: E/TiApplication(6234):  at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:185)
02-22 18:28:32.967: E/TiApplication(6234):  at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:109)`

It seems that the module needs to be recompiled to support Android 6.0 relocation

Thank you
Alessandro

**Comment by cjadhav** [comment]
Hi,
Did you got this working??
I am also facing same error.
Or did you moved to another module??

Your help is highly appreciated.

**Comment by facco88** [comment]
The module is still not working, can anyone take a look at it, please?
